### ISSUE TITLE
Contact of Index Patient not syncing to server if Index Patient created under Data Entry area

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#63]
I have an Index Patient whose parent is the Data Entry Area.  If I submit a Trace Request for that Index Patient, the contacts created from the Trace Request do not replicate to the server and I get an error. 

Logged in as `nate` who is the primary contact of `Data Entry - Nate Smith`.  I select `Nora Hopson` and then "New Action | Trace Request Form".  The contact that I entered in the Trace Request Form was "Lindy Holms". You can see the "Denied replicating to remote server" error in the console.

[Here](https://drive.google.com/file/d/19qfsDAHlcnEH5Q0SLgQ1pNRUbzuJFH9p/view?usp=sharing) is a video of me recreating this issue.

![Screen Shot 2020-04-20 at 11 58 41 PM](https://user-images.githubusercontent.com/10096985/79823919-e29a0600-8362-11ea-8ce8-37c6036e3f2f.png)

**Comment by senseibara** [comment]
thanks @michaelkohn , cc-ing : @binokaryg i remembered we had a discussion on this but can't remember what was the last conclusion. In my memories it was possible to create a P0 at both level 2 or Level 3 and for any of them the trace request would generate contacts that will be replicated just fine, is it not the case ? IF not what would you advise for switching ? I Guess michael's preference would be to create P0 at level 2

**Comment by binokaryg** [comment]
The `covid_trace_request` form assumes that P0 is at level 3 (separate place for Patient Zeros).
When we add a new tracing contact using the form, it gets parent hierarchy for the newly created contact with this information:
- parent._id -> `tracer_area` selected from the dropdown
- parent.parent._id -> `../inputs/contact/parent/parent/_id`
- parent.parent.parent._id -> `../inputs/contact/parent/parent/parent/_id`

If P0 is at level 2 instead, it does not have `parent.parent.parent` information, so the hierarchy is not valid. I suspect that this is the reason why the replication fails.

If P0 will be at level 2 only, the parent hierarchy for tracing contacts can be configured as:
- parent._id -> `tracer_area` selected from the dropdown
- parent.parent._id -> `../inputs/contact/parent/_id`
- parent.parent.parent._id -> `../inputs/contact/parent/parent/_id`

Ideally, if we could get the ancestral information from the selected `tracer_area` directly, it would work regardless of the position of the P0. I had tried doing that but got into a problem because of duplicate group names.

**Comment by michaelkohn** [comment]
That's fine, thanks. For the demo I can accept that they are required to have a `clinic` as a parent.

**Comment by michaelkohn** [comment]
Is https://github.com/medic/config-covid/issues/62 related though?  The form seems to be trying to access P0 but the Tracer doesn't have access to P0.

**Comment by binokaryg** [comment]
It looks like pulling the ancestral information directly from `tracer_area` works if we keep it inside a separate group so that the group name `parent` does not clash with another group with the same name.

Changes made:
- Add a group named `tracer` and keep `tracer_area` inside it.
- Change `appearance` of `tracer_area` from `db-object bind-id-only` to `db-object`
- Add parent groups inside the `tracer` group
- Refer the inner parent groups from outside

type | name | label | appearance | calculation
-- | -- | -- | -- | --
**begin group** | **tracer** |   |   |  
db:clinic | tracer_area | Tracer Area | **db-object** |  
begin group | parent | NO_LABEL |   |  
hidden | _id | Parent |   |  
begin group | parent | NO_LABEL |   |  
hidden | _id | Area |   |  
begin group | parent | NO_LABEL |   |  
hidden | _id | Health Facility ID |   |  
end group | parent |   |   |  
end group | parent |   |   |  
end group | parent |   |   |  
**end group** | **tracer** |   |   |  
begin group | parent | NO_LABEL |   |  
calculate | _id | Parent |   | ../../tracer/tracer_area
begin group | parent | NO_LABEL |   |  
calculate | _id | Area |   | ../../../tracer/parent/_id
begin group | parent | NO_LABEL |   |  
calculate | _id | Health Facility ID |   | ../../../../tracer/parent/parent/_id
end group | parent |   |   |  
end group | parent |   |   |  
end group | parent |   |   |  

Updated form: [covid_trace_request.xlsx](https://github.com/medic/config-covid/files/4510280/covid_trace_request.xlsx)

Please note that the `properties.json` needs to be changed accordingly so that the form is accessible.

**Comment by binokaryg** [comment]
Fixed and [pushed ](https://github.com/medic/config-covid/commit/859054563df094fa6102c6d5f8bbd1ffb04319f6)to the branch `covid_refinements`, and also to the instance.
